config/routes.rb
Rails.application.routes.draw do

  get  'products/import'

  post 'products/import_process'
  
  get 'products/export_manu'
  get 'products/export_cat'
  post 'products/export_manu'
  post 'products/export_cat'
  get  'products/import_format' 
  get  'products/main_category'

  post 'products/main_category'

  get  'products/sub_category'

  post 'products/sub_category'

  get  'products/product_desc'

  post 'products/product_desc'

  get  'products/product_compare'

  post 'products/product_compare'

  
  get  'products/manu_category'

  post 'products/manu_category'

  get  'products/manu_category_sub'

  post 'products/manu_category_sub'

  get  'products/manu_category_desc'

  post 'products/manu_category_desc'

  get  'products/manu_category_compare'

  post 'products/manu_category_compare'

  get  'products/manu_index_category'

  post 'products/manu_index_category'

  get  'products/manu_index_sub_category'

  post 'products/manu_index_sub_category'

  get  'products/manu_index_product_desc'

  post 'products/manu_index_product_desc'

  get  'products/manu_index_product_compare'

  post 'products/manu_index_product_compare'
  
  get  'products/manu_index_product_filter'

  post 'products/manu_index_product_filter'

  
  get 'products/search'
  
  post 'products/search'

  get 'products/search_desc'

  post 'products/search_desc'

  get "products/login_page"
  post "products/validate_login"

  get "products/logout"
  post "products/logout"

  get 'products/new'
  
  post 'products/create'
  get 'products/main'
  post 'products/main'

   root 'products#main_category'

end

app/models/product.rb
require 'spreadsheet'

require 'roo'

require 'csv'

require 'byebug'

class Product

  include Mongoid::Document 
  
  field :item_id
  
  field :glo_desc
  
  field :product_name
  
  field :mp_number
  
  field :taxon_id
  
  field :taxonomy_id
  
  field :manu_id
  
  field :html
  
  field :pdf
  
  field :image
  
  field :d_long
  
  field :d_short
  
  field :d_bullet
  
  field :d_copy
  
  field :extra
  
  field :property
  
  field :path

  field :property_extra

  index( { manu_id: 1},{ background: true } )
  index( { taxon_id: 1},{ background: true } )
  index( { id: 1},{unique: true} )
  index( { taxonomy_id: 1},{ background: true } )
  index( { product_name: 1},{ background: true } )
  index( { glo_desc: 1},{ background: true } )
  index( { image: 1},{ background: true } )

  def self.bro(file)
  case File.extname(file.original_filename)
  
  when ".csv" 
@file = File.open(file.tempfile,"r").collect{|p| p.chomp.split("\t")}  
#@file = File.open(file.tempfile,"r").collect{|o| o.chomp.split("\t")}
#    @file=CSV.read(file.tempfile)
  when ".txt" 
  
    #byebug

    @ff=File.open(file.tempfile, "r",:headers=>true)
    
    @ss=@ff.collect{|p| p.encode!('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')}

    @file=@ss.collect{|a|a.chomp.split(",").collect{|a| a.split("\t")}}
    
  when ".xlsx" 
  
    @file=File.open(file.tempfile,"r").collect{|p| p.chomp.split("\t")}
    
  end
   @head=["ID", "M Number", "M Name", "M Logo", "GD", "T", "H1", "P1", "P2", "I1", "D Copy", "D Bullet", "D Long", "D Short", "Name", "A1", "A2", "A3"]
if  @file.collect{|p| @head.include?(p)}.count(true) == @head.count
       
    @id=@file[0].index("ID")
    
    @gd=@file[0].index("GD")
    
    @mn=@file[0].index("M Name")
    
    @ml=@file[0].index("M Logo")
    
    @mpn=@file[0].index("M Number")
    
    @pn=@file[0].index("Name")
    
    @dl=@file[0].index("D Long")
    
    @ds=@file[0].index("D Short")
    
    @dc=@file[0].index("D Copy")
    
    @db=@file[0].index("D Bullet")
    
    @tax=@file[0].index("T")

    @html=@file[0].select{|a| a.start_with?("H")}.map{|i| @file[0].index(i)}.compact
    
    @extra=@file[0].select{|a| a.start_with?("E")}.map{|i| @file[0].index(i)}.compact
    
    @pdf=@file[0].select{|a| a.start_with?("P")}.map{|i| @file[0].index(i)}.compact
    
    @img=@file[0][1..-1].select{|a| a.start_with?("I")}.map{|i| @file[0].index(i)}.compact

    @attrstartloc=@file[0].index{|i| i.starts_with?("A")}
    
    @tax_ids=[]
    
    $upcount,$newcount=[],[];
   
    @file.each do |line|

   
      next if line[0].match(/[0-9]/) == nil
   
        @taxonomy= line[@tax].split('>')
   
      unless Taxon.where(:main_cat_name=>@taxonomy[0]).present?
   
        @taxon=Taxon.new(:main_cat_name=>@taxonomy[0])
   
        @taxon.save(:validate=>true)
   
      end
   
      taxon=@taxonomy[0]
   
      @taxon_id=Taxon.where(:main_cat_name=>@taxonomy[0]).pluck(:id)[0]
   
     @taxonomy[1..-1].each do |tax|

        if Taxon.where(:main_cat_name=>taxon).present?
        
          @p_id=Taxon.where(:main_cat_name=>taxon).pluck(:id)[0]
        
        elsif Taxonomy.where(:sub_cat_name=>taxon).present?
        
          @p_id=Taxonomy.where(:sub_cat_name=>taxon).pluck(:id)[0]
        
        end
        
        unless Taxonomy.where(:sub_cat_name=>tax).where(:parent_id=>@p_id).present?
        
          @taxonomy=Taxonomy.new(:sub_cat_name=>tax,:parent_id=>@p_id,:taxon_id=>@taxon_id)
        
          @taxonomy.save
        
        end
        
        taxon=tax
        
        @taxonomy_id=Taxonomy.where(:sub_cat_name=>tax,:parent_id=>@p_id,:taxon_id=>@taxon_id).pluck(:id)[0]
        
        @tax_ids <<  @taxonomy_id
        
      end
      
      unless @extra.empty?
      
        @extra_data=@extra.map{|p| Hash[@file[1][p]=>line[p]]}
      
      end
        
       
      unless Manufacture.where(:manu_name=>line[@mn]).present?
      
        @manu=Manufacture.new(:manu_name=>line[@mn],:manu_logo=>line[@ml])
      
        @manu.save
      
      end
      
        @manu_id=Manufacture.where(:manu_name=>line[@mn],:manu_logo=>line[@ml]).pluck(:id)[0]
      
        @html_link=@html.map{|p| line[p]}.compact
      
        @pdf_link=@pdf.map{|p| line[p]}.compact
      
        @img_link=@img.map{|p| line[p]}.compact
      
        @attri_data=line[@attrstartloc..-1].each_slice(3).to_a
          
        @attribute_data = @attri_data.reject{|p| p[0]==nil || p[1]==nil}.map{|p| [p[0],p[1..-1].compact.join('  ')]}

        @attribute_data1 = @attri_data.reject{|p| p[0]==nil || p[1]==nil}.map{|p| {p[0]=>p[1..-1].compact.join('  ')} }

        if Manufacture.where(:manu_name=>line[@mn]).present?
  
          @man=BSON::ObjectId.from_string(Manufacture.where(:manu_name=>line[@mn]).pluck(:id)[0])

        end

        if Product.where(:manu_id=>@man).where(:mp_number=>line[@mpn]).present?

         Product.where(:manu_id=>@man).where(:mp_number=>line[@mpn]).delete
        @product=Product.new(:item_id=>line[@id],:glo_desc=>line[@gd],:product_name=>line[@pn],:mp_number=>line[@mpn],
        :taxon_id=>@taxon_id,:taxonomy_id=>@taxonomy_id,:manu_id=>@manu_id,:html=>@html_link,
        :pdf=>@pdf_link,:image=>@img_link,:d_long=>line[@dl],:d_short=>line[@ds],
        :d_bullet=>line[@db],:d_copy=>line[@dc],:extra=>@extra_data,:property=>Hash[*@attribute_data.flatten],:path=>@tax_ids.flatten.compact.uniq.sort,:property_extra=>@attribute_data1)

        @product.save(validate=>true)
        $upcount << @product

        else
        @product=Product.new(:item_id=>line[@id],:glo_desc=>line[@gd],:product_name=>line[@pn],:mp_number=>line[@mpn],
        :taxon_id=>@taxon_id,:taxonomy_id=>@taxonomy_id,:manu_id=>@manu_id,:html=>@html_link,
        :pdf=>@pdf_link,:image=>@img_link,:d_long=>line[@dl],:d_short=>line[@ds],
        :d_bullet=>line[@db],:d_copy=>line[@dc],:extra=>@extra_data,:property=>Hash[*@attribute_data.flatten],:path=>@tax_ids.flatten.compact.uniq.sort,:property_extra=>@attribute_data1)
  
        @product.save(validate=>true)
        $newcount << @product
        end
        @tax_ids.clear
  
    end
  end
  end

#def as_indexed_json
#    as_json(except: [:id, :_id])
 # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

skip_before_filter :verify_authenticity_token, only: [:product_compare,:manu_category_compare,:manu_index_product_compare]
#skip_before_action :check_session, :only=>[:main_category,:sub_category,:product_desc,:product_compare,:manu_category,:manu_category_desc,:manu_category_compare,:manu_index_category, :manu_index_sub_category, :manu_index_product_desc,:manu_index_product_compare,:search,:search_desc,:login_page,:validate_login,:import,:export_manu,:export_cat,:import_format]

require 'will_paginate/array'
def main
 redirect_to root_path
end
def new
  @user=User.new
  render :layout=>false
end

def create
  @user=User.new(user_params)
    if @user.save
      redirect_to :action=>"login_page"
    else
      redirect_to :action=>"new"
    end
end

def login_page
  @user=User.new
end
def validate_login
 params.permit!
 @user=User.where params[:user]
 if not @user.blank?
  session[:user_id]=@user.first.id
  redirect_to :action=>"import"
  else
  redirect_to root_path 
  end
end


  def import

     @product=Product.new

     render :layout=>false
  end

  def import_process

     file=params[:product][:file1]

     filename=params[:product][:file1].original_filename

     @product=Product.bro(file)
    
     unless @product.blank?
    
     redirect_to :action=> "import"
 
     flash[:notice] = "Your file has been successfully imported in a database..."
   
     else

     flash[:notice] = "Invalid file headers or file format"
     
     redirect_to :action=> "import"
    
     end

  end


  def import_format
 
     send_file Rails.root.join('public/files', 'sample.xls'), :type=>"application/xls", :x_sendfile=>true

 end

  def export_cat

    ss=params[:product][:id]
    
    $export_cat=Product.where(:taxon_id=>BSON::ObjectId("#{ss}"))
    unless $export_cat.pluck(:extra)[0].nil?
    @extra=$export_cat.pluck(:extra)[0].keys
    end
  
    @taxon=Taxon.all

  end  

 def export_manu
 #byebug
 ss=params[:product][:id]
    
    $export_manu=Product.where(:manu_id=>BSON::ObjectId("#{ss}"))
    unless $export_manu.pluck(:extra)[0].nil?
    @extra=$export_manu.pluck(:extra)[0].keys
    end
 end

  def main_category

      @taxon=Taxon.all    
      
      @manufacture=Manufacture.all

      #@taxon_id=params[:format] || params[:id]

      #@product=Product.all

      #@im=@product.where(:main_cat_name=>@taxon_id).pluck(:image)[0]

  end

  def sub_category

    unless params.include?("is")
      @taxon_id = params[:format] || params[:id]
    end
              
      unless params.include?("is") || Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).present?



        if Taxon.where(:id=>@taxon_id).present?
          @main_cat_name=Taxon.where(:id=>@taxon_id)
          $main_cat_name=Taxon.where(:id=>@taxon_id)
          $taxon_main=Taxonomy.where(:taxon_id=>BSON::ObjectId.from_string(@taxon_id))

          @taxon=$taxon_main.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id))
        

        else
          @main_cat_name=Taxon.where(:id=>Taxonomy.where(:id=>BSON::ObjectId.from_string(@taxon_id)).pluck(:taxon_id)[0])
          $main_cat_name=@main_cat_name
          if $taxon_main.blank? || $taxon_main.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id)).blank?
            @taxon=Taxonomy.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id))
          else
            @taxon=$taxon_main.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id))
          end
          @ta=@taxon.pluck(:parent_id)[0]

        end

      else
        if params.include?("is")
          @product1=Product.where(:id.in=>params[:is].join(' ').split(' ').uniq)
          @ta=@product1.pluck(:taxonomy_id).uniq[0]
          @taxon_id=@product1.pluck(:taxonomy_id).uniq[0]
          @main_cat_name=Taxon.where(:id=>@product1.pluck(:taxon_id)[0])
        else
          @main_cat_name=Taxon.where(:id=>Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).pluck(:taxon_id)[0])
          @product1=Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id))
          @ta=@taxon_id
        end
          @product=@product1.paginate(:page => params[:page], :per_page => 10)
      end
      $taxo=[]
        unless Taxon.where(:id=>@taxon_id).present?


          begin
              s=BSON::ObjectId.from_string(@main_cat_name.pluck(:id)[0])
              if Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).present?
                @tax=Taxonomy.where(:id=>BSON::ObjectId.from_string(@ta))
              else
                @tax=Taxonomy.where(:id=>BSON::ObjectId.from_string(@ta))
              end
              tax1=Taxonomy.where(:id=>BSON::ObjectId.from_string(@ta)).pluck(:parent_id)[0]
              $taxo<<@tax
              @ta=@tax.pluck(:parent_id)[0]



          end until tax1==s
        end
  end

  def product_desc

       
    @prms=params[:format]
    @product=Product.where(:id=>BSON::ObjectId.from_string(params[:format]))
    @related=Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@product.pluck(:taxonomy_id)[0])).not.where(:id=>@product.pluck(:_id))

  end

  def product_compare
    @comp=[]
    if params.include?("is")

      $pros=Product.where(:id.in=>params[:is].flatten.uniq)
      $pros.pluck(:property).map{|i| @comp << i.keys}
    else
      
      $pros1=$pros.flatten-$pros.flatten.select{|p| p.item_id == params[:format]}
      $pros.clear
      $pros=$pros1
      $pros.map{|p| @comp << p.property.keys}
    end
      
 
      

      @names=["","manu_name","mp_number","product_name","image",[@comp.flatten.uniq]].flatten
    
  end

  def manu_category

    unless params.include?("is")
      @taxon_id = params[:format] || params[:id]
    end

    unless params.include?("is") || Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).present?
      
      if Product.where(:manu_id=>BSON::ObjectId.from_string(@taxon_id)).present?
    
        @manu_id=@taxon_id
    
        $manu_name=Manufacture.where(:id=>@manu_id)
    
        @taxon=Taxon.where(:id.in=>Product.where(:manu_id=>BSON::ObjectId.from_string(@manu_id)).pluck(:taxon_id).flatten.uniq).flatten
   
        $taxonomy=Taxonomy.where(:id.in=>Product.where(:manu_id=>BSON::ObjectId.from_string(@manu_id)).pluck(:path).flatten.compact.uniq)
           

      else

        @taxon=$taxonomy.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id))
        @main=Taxon.where(:id=>@taxon.pluck(:taxon_id)[0])
        $main=Taxon.where(:id=>@taxon.pluck(:taxon_id)[0])
        @ta=@taxon.pluck(:parent_id)[0]
      end

    else

      if params.include?("is")

          @product1=Product.where(:id.in=>params[:is].join(' ').split(' ').uniq)
          @ta=@product1.pluck(:taxonomy_id).uniq[0]
          @taxon_id=@product1.pluck(:taxonomy_id).uniq[0]
          @main=Taxon.where(:id=>@product1.pluck(:taxon_id)[0])
        else

        @product1=Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).where(:manu_id=>BSON::ObjectId.from_string($manu_name.pluck(:id)[0]))
        @main=Taxon.where(:id=>@product1.pluck(:taxon_id)[0])
        @ta=@taxon_id
        end
         @product=@product1.paginate(:page => params[:page], :per_page => 10)

    end
$taxo1=[]
 unless Manufacture.where(:id=>@taxon_id).present? || Taxon.where(:id=>@taxon_id).present?
     begin
      
       s=BSON::ObjectId.from_string(@main.pluck(:id)[0])
          
          
            
            @tax=Taxonomy.where(:id=>BSON::ObjectId.from_string(@ta))
          
        tax1=Taxonomy.where(:id=>BSON::ObjectId.from_string(@ta)).pluck(:parent_id)[0]
     
     
     
 $taxo1<<@tax

 @ta=@tax.pluck(:parent_id)[0]

end until tax1==s
end
  end

  def manu_category_sub

  end

  def manu_category_compare

@comp=[]
    if params.include?("is")

      $pros1=Product.where(:id.in=>params[:is].flatten.uniq)
      $pros1.pluck(:property).map{|i| @comp << i.keys}
    else

      $pros11=$pros1.flatten-$pros1.flatten.select{|p| p.item_id == params[:format]}
      $pros1.clear
      $pros1=$pros11
      $pros1.map{|p| @comp << p.property.keys}
    end
      
 
      

      @names=["","manu_name","mp_number","product_name","image",[@comp.flatten.uniq]].flatten
    
            
  end

  def manu_category_desc
  
   
    @prms=params[:format]
    @product=Product.where(:id=>BSON::ObjectId.from_string(params[:format]))
@related=Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@product.pluck(:taxonomy_id)[0])).where(:manu_id=>BSON::ObjectId.from_string(@product.pluck(:manu_id)[0])).not.where(:id=>@product.pluck(:_id))
    
  end

  
  def manu_index_category

    @taxon=Taxon.all

  end

  def manu_index_sub_category
 
 unless params.include?("is")
      @taxon_id = params[:format] || params[:id]
    end

     unless params.include?("is") || Product.where(:taxonomy_id=>BSON::ObjectId.from_string(@taxon_id)).present? 
      if Taxon.where(:id=>BSON::ObjectId.from_string(@taxon_id)).present?
          @tax=@taxon_id
          $taxon_name=Taxon.where(:id=>@taxon_id)
          @main=$taxon_name
          $main=$taxon_name

          @manufacture=Manufacture.where(:id.in=>Product.where(:taxon_id=>BSON::ObjectId.from_string(@taxon_id)).pluck(:manu_id).uniq)
      elsif Product.where(:manu_id=>BSON::ObjectId.from_string(@taxon_id)).present?
          $manufacture=Manufacture.where(:id=>@taxon_id)
          $manu=$manufacture.pluck(:manu_name)[0]
          $taxonomy_index=Taxonomy.where(:id.in=>Product.where(:manu_id=>BSON::ObjectId.from_string(@taxon_id)).pluck(:path).flatten.uniq.sort)
          @sub_taxonomy=$taxonomy_index.where(:parent_id=>BSON::ObjectId.from_string($taxon_name.pluck(:id)[0]))
          @main=Taxon.where(:id=>@sub_taxonomy.pluck(:taxon_id)[0])
          @ta=@sub_taxonomy.pluck(:parent_id)[0]
      else
          @sub_taxonomy=$taxonomy_index.where(:parent_id=>BSON::ObjectId.from_string(@taxon_id))
          @main=Taxon.where(:id=>@sub_taxonomy.pluck(:taxon_id)[0])

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/manu_category_compare.html.erb
<body onload="noBack();" onpageshow="if (event.persisted) noBack();" onunload="">
<div class="body-wrap">

  <div class="body-container">

    <div class="body-header">Product Compare</div>

      <div class="body-content">
    
        <div class="container">
          <div class="row">

                          <div class="col-md-12">

        <%unless Manufacture.where(:id=>params[:format]).present?%>
                            <ol class="breadcrumb">
                                
        <% @taxo=[$taxo1.flatten+$main.flatten].flatten.reverse%>

                                

 <% @taxo.each do |i|%>

<% if Taxon.where(:id=>i.id).present?%>
<li><%=link_to i.main_cat_name, products_manu_category_path(i.id)%></li>
<%else%>
 <li><%=link_to i.sub_cat_name, products_manu_category_path(i.id)%></li>
 <%end%>
                                
                                <%end%>
                
                               
        
                            </ol>
                            <%end%>
        
                        </div>
        
                    </div>
          <div class="row">
      
            <div class="col-md-12">
      
              <div class="product-compare">
      
                <table class="table">

                  <i class="fa fa-dot-circle-o" style="font-size: 15px; color: rgb(0, 102, 255);"></i>&nbsp;Indicates product differences.<br><br>

                   

                    <%t=1%>

                      <%@names.each do |i|%>

                        <tr>

                          <%if t < 6 %>

                            <td></td>

                              <%$pros1.each do |p|%>
                              <%if t == 1%>
                              <td><%=link_to_if $pros1.count > 2,"Remove item", products_manu_category_compare_path(p.item_id)%></td>
                                <%elsif t == 2 %>
                                     
                                  <%@temp=Manufacture.where(:id=>BSON::ObjectId.from_string(Product.where(:id=>p.id).pluck(:manu_id)[0])).pluck(i.to_sym)[0]%>

                                  <td style="background-color: #242d35; color:white;"><strong><%=@temp%></strong></td>


                                <%elsif t == 5%>

                                  <td><%=image_tag p.image[0]%></td>    

                                <%elsif t == 3%>
                                                                   
                                 <td><%= link_to Product.where(:id=>p.id).pluck(i.to_sym)[0],products_manu_category_desc_path(p.id)%></td>
                                 <%else%>
                                  <td><%=Product.where(:id=>p.id).pluck(i.to_sym)[0]%></td>
                                <%end%>
                                
                              <%end%>

                      
                              
                          <%else%>
                          
                          <tbody>

                            <%@pp=[]%>

                         <%$pros1.each{|l| @pp << Product.where(:id=>l.id).pluck(:property)[0][i]}%>

                            <%if @pp.uniq.count > 1%>

                             <td><i class="fa fa-dot-circle-o" style="font-size: 15px; color: rgb(0, 102, 255);"></i>&nbsp;<%=i%></td> 

                          <%else%>

                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=i%></td>

                          <%end%>
                          
                              <%$pros1.each do |p|%>

                                <%@temp=Product.where(:id=>p.id).pluck(:property)[0]%>

                                <%if @pp.uniq.count > 1%>
                                <td style="color: rgb(0, 102, 255);"><%=@temp[i]%></td>
                                <%else%>
                                <td><%=@temp[i]%></td>

                                <%end%>
                              <%end%>

                          <%end%>

                        </tr>
                        
                        <%t=t+1%>
                        
                      <%end%>
                                              
                   </tbody>
                  
                </table>
                
              </div>

            </div>

          </div>

        </div>
                        
       <div class="clearfix"></div>
                           
      </div>

    <div class="clearfix"></div>

  </div>
 
 <div class="clearfix"></div> 

</div>
</body>
<script type="text/javascript">
    window.history.forward();
    function noBack() { window.history.forward(); }
</script>


app/views/products/manu_index_category.html.erb
            <div class="body-wrap">
                <div class="body-container">
                    <div class="body-header">
                        Manufatures Index
                    </div>
                    <div class="body-content">
                      <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <span class="sub-title">Please choose a product category to view the manufacturers in that category. </span>
                            </div>
                        </div>
                        <div class="row">
                            <%@taxon.order("main_cat_name ASC").map do |i|%>
                            <div class="col-md-6">
                                <div class="manufacture-index hvr-sweep-to-right">  
                                    <%=link_to i.main_cat_name,products_manu_index_sub_category_path(i) %>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <%end%>
                        <div class="clearfix"></div>
                        </div>
                      </div>
                            <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
               <div class="clearfix"></div> 
            </div>

app/views/products/manu_index_product_compare.html.erb
<div class="body-wrap">

 	<div class="body-container">

   	<div class="body-header">Product Compare</div>

      <div class="body-content">
    
        <div class="container">
           <div class="row">
         
                        <div class="col-md-12">

         
                            <ol class="breadcrumb">


                              <% @taxo=[$taxo2.flatten+$main.flatten].flatten.reverse%>

                                

 <% @taxo.each do |i|%>

<% if Taxon.where(:id=>i.id).present?%>
<li><%=link_to i.main_cat_name, products_manu_index_sub_category_path(i.id)%></li>
<%else%>
 <li><%=link_to i.sub_cat_name, products_manu_index_sub_category_path(i.id)%></li>
 <%end%>
                                
                                <%end%>
                
                               
        
                            </ol>
        
                        </div>
        
                    </div>
		
          <div class="row">
      
            <div class="col-md-12">
      
              <div class="product-compare">
      
                <table class="table">

                  <i class="fa fa-dot-circle-o" style="font-size: 15px; color: rgb(0, 102, 255);"></i>&nbsp;Indicates product differences.<br><br>

                   

                    <%t=1%>

                      <%@names.each do |i|%>

                        <tr>

                          <%if t < 6 %>

                            <td></td>

                              <%$pros2.each do |p|%>
                              <%if t == 1%>
                              <td><%=link_to_if $pros2.count > 2,"Remove item", products_manu_index_product_compare_path(p.item_id)%></td>
                                <%elsif t == 2 %>
                                     
                                  <%@temp=Manufacture.where(:id=>BSON::ObjectId.from_string(Product.where(:id=>p.id).pluck(:manu_id)[0])).pluck(i.to_sym)[0]%>
                          <td style="background-color: #242d35; color:white;"><strong><%=@temp%></strong></td>
                                <%elsif t == 5%>

                                  <td><%=image_tag p.image[0]%></td>    

                                <%elsif t == 3%>
                                                                   
                                 <td><%= link_to Product.where(:id=>p.id).pluck(i.to_sym)[0],products_manu_index_product_desc_path(p.id)%></td>
                                 <%else%>
                                  <td><%=Product.where(:id=>p.id).pluck(i.to_sym)[0]%></td>
                                <%end%>
                                
                              <%end%>

                      
                              
                          <%else%>
                          
                          <tbody>

                            <%@pp=[]%>

                         <%$pros2.each{|l| @pp << Product.where(:id=>l.id).pluck(:property)[0][i]}%>

                            <%if @pp.uniq.count > 1%>

                             <td><i class="fa fa-dot-circle-o" style="font-size: 15px; color: rgb(0, 102, 255);"></i>&nbsp;<%=i%></td> 

                          <%else%>

                            <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=i%></td>

                          <%end%>
                          
                              <%$pros2.each do |p|%>

                                <%@temp=Product.where(:id=>p.id).pluck(:property)[0]%>

                                <%if @pp.uniq.count > 1%>
                                <td style="color: rgb(0, 102, 255);"><%=@temp[i]%></td>
                                <%else%>
                                <td><%=@temp[i]%></td>

                                <%end%>
                              <%end%>

                          <%end%>

                        </tr>
                        
                        <%t=t+1%>
                        
                      <%end%>
                                              
                   </tbody>
                  
                </table>
                
              </div>

            </div>

          </div>

        </div>
                        
       <div class="clearfix"></div>
                           
      </div>

    <div class="clearfix"></div>

  </div>
 
 <div class="clearfix"></div> 

</div>