config/routes.rb
Rails.application.routes.draw do

  get  'products/import'

  post 'products/import_process'
  
  get 'products/export_manu'
  get 'products/export_cat'
  post 'products/export_manu'
  post 'products/export_cat'
  get  'products/import_format' 
  get  'products/main_category'

  post 'products/main_category'

  get  'products/sub_category'

  post 'products/sub_category'

  get  'products/product_desc'

  post 'products/product_desc'

  get  'products/product_compare'

  post 'products/product_compare'

  
  get  'products/manu_category'

  post 'products/manu_category'

  get  'products/manu_category_sub'

  post 'products/manu_category_sub'

  get  'products/manu_category_desc'

  post 'products/manu_category_desc'

  get  'products/manu_category_compare'

  post 'products/manu_category_compare'

  get  'products/manu_index_category'

  post 'products/manu_index_category'

  get  'products/manu_index_sub_category'

  post 'products/manu_index_sub_category'

  get  'products/manu_index_product_desc'

  post 'products/manu_index_product_desc'

  get  'products/manu_index_product_compare'

  post 'products/manu_index_product_compare'
  
  get  'products/manu_index_product_filter'

  post 'products/manu_index_product_filter'

  
  get 'products/search'
  
  post 'products/search'

  get 'products/search_desc'

  post 'products/search_desc'

  get "products/login_page"
  post "products/validate_login"

  get "products/logout"
  post "products/logout"

  get 'products/new'
  
  post 'products/create'
  get 'products/main'
  post 'products/main'

   root 'products#main_category'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Product Catalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Altius Product Catalog</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
    <meta name="description" content="Source code generated using layoutit.com">
     <meta name="author" content="LayoutIt!">

</head>

<style>
      
.menu {
 float: right;
 position: absolute;
border: 1px solid #b6acac;
background: #fff;
left: 29%;
width: 50%;
height:50%;
padding: 40px;
border-radius: 10px;
cursor: pointer;
}

</style>
<script type="text/javascript">
    
</script>

 <body>
  <div id="header-container">
  <div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
                <div class="left-container">
                    <div class="menu-icon">
                    <i class="fa fa-outdent" aria-hidden="true" style="font-size: 33px; color: rgb(6, 173, 195);"></i>
                    </div>
                     <div class="search-box">
                        <div class="form-group">
                          <%= form_tag(action: "search", :method => "get", id: "search-form") do %>
                            <input id="search" name="search"  class="form-control" type="text" placeholder="Search">
                                <button class="btn btn-block btn-default" >
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                </button>
                                <%end%>
                        </div>
                    </div>
                </div>
                <div class="logo-container">
                    <%= link_to image_tag("/assets/logo.png"),root_path,:title=>"Goto Home..." %>
                </div>
                <div class="right-container">
                     
<!--<button class="btn btn-block btn-default hvr-sweep-to-right" controller="products" action="login_page"><i class="fa fa-key" aria-hidden="true"></i>
    Login</button>-->
                                               
                </div>
            
        </div>
    </div>
  </div>
  </div>
    

<div class="container-fluid">
    <div class="row  wrapper">

   <%@pa=params[:id] || params[:format] %>

              <%unless @pa == nil || params[:action] == "search" || params[:action] == "product_compare" || params[:action] == "manu_index_product_compare" || params[:action] == "manu_category_compare" %>

                <%@paq=BSON::ObjectId.from_string(@pa)%>
              
              <%end%>
              
              <%unless Product.where(:taxonomy_id=>@paq).present? || params[:action] == "search" %>
              
            <div class="sidebar">
            
            <div id="scroll">
            <div class="panel-collapse  panel-scroll" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><i class="fa fa-th" aria-hidden="true"></i> Categories </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                 <%Taxon.all.order("main_cat_name ASC").map do |i|%>
                                <li><%= link_to i.main_cat_name,products_sub_category_path(i) %> </li>
                                  <%end%>
                            </ul>
                           
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><i class="fa fa-cogs" aria-hidden="true" ></i> Manufacturer</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse ">
                        <div class="panel-body">
                            <ul>
                                <%Manufacture.all.order("manu_name ASC").map do |i|%>
                                  <li><%=link_to i.manu_name,products_manu_category_path(i) %></li>                                                           
                                  <%end%>
                            </ul>
                           
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="/products/manu_index_category"><i class="fa fa-database" aria-hidden="true">   </i> View Manufaturers Index</a>
                        </h4>
                    </div>
                    </div>
                
            
                                <div class="clearfix"></div>
            </div>
            
            </div>
            
                
                <div class="clearfix"></div>
                 <div class="follow-container">Follow Us on
            <div class="social">
    <a target="_blank" href="https://www.facebook.com/" ><i class="fa fa-facebook" title="Facebook"></i></a>
    <a target="_blank" href="https://www.twitter.com/" ><i class="fa fa-twitter" aria-hidden="true" title="Twitter"></i></a>
     <a target="_blank" href="https://www.google-plus.com/" ><i class="fa fa-google-plus" aria-hidden="true" title="Google-Plus"></i></a>
        <a target="_blank" href="https://www.pinterest.com/" ><i class="fa fa-pinterest" aria-hidden="true" title="Pinterest"></i></a>
        <a target="_blank" href="https://www.envelope.com/" ><i class="fa fa-envelope" aria-hidden="true" title="Envelope"></i></a>
         <a target="_blank" href="https://www.linkedin.com/" ><i class="fa fa-linkedin" aria-hidden="true" title="linkedin"></i></a>
                   </div><!--close social -->  
                   <div class="clearfix"></div>
                 </div><!--close  follow -->
                 <div class="footer-container">
                © 2016 Altiusproductcatalog.com
                <a target="_blank" href="https://www.altiustechnology.com/" >All rights reserved.</a>
                <div class="clearfix"></div>
                </div><!--close footer -->

    </div>
    <div class="clearfix"></div>

            
            
            
               <div class="clearfix"></div>

<%else%>
    <%@act=params[:action]%>
  <%case @act%>
  <%when "search"%>
  <%@property=Product.where(:id.in=>$prod.flatten.uniq)%>
  <%when "sub_category"%>
  <%@property=Product.where(:taxonomy_id=>@paq)%>
  <%when "manu_category"%>
  <%@property=Product.where(:taxonomy_id=>@paq).where(:manu_id=>BSON::ObjectId.from_string($manu_name.pluck(:id)[0]))%>
  <%when "manu_index_sub_category"%>
  <%@property=Product.where(:taxonomy_id=>@paq).where(:manu_id=>BSON::ObjectId.from_string($manufacture.pluck(:id)[0]))%>
  <%end%>
  
  <%@names=@property.pluck(:property).flatten.map{|p| p.keys}.flatten.flatten.uniq%>
  <%@pros=@property.pluck(:id,:property)%>
  <div class="filterbar">
    <form controller="products" action="#{params[:action]}" accept-charset="UTF-8" method="get" name="form1" onsubmit="return validat()">
            <div class="headbar">
              Filter By  
              <input name="commit" value="Apply"  id="bt_submit" type="submit" class="btn btn-block btn-default hvr-sweep-to-right">
              
                <div class="clearfix"></div>
            </div>

            <div class="clearfix"></div>
            <div id="scroll">
            <div class="panel-collapse  panel-scroll" id="accordion">
                <%t=1%>
                <%@names.each do |n|%>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=t%>">
                                <i class="fa fa-filter" aria-hidden="true"></i> <%=n%></a>
                        </h4>
                    </div>
                    <div id="collapse<%=t%>" class="panel-collapse collapse">
                        <div class="panel-body">
                          <ul>
                            <%@check=[]%>
                            <%@pros.each do |pp|%>
                            <%next if pp[1][n] == nil%>
                            <%next if @check.include?(pp[1][n])%>
                            <%@id=@property.where(:property_extra=>{n=>pp[1][n]}).pluck(:id)%>
                                                           <li>

                              <div class="checkbox">

                                <label>

                                  <%=check_box_tag 'is[]', @id, false,{:onclick=>"chkcontrol();"}%>

                                     <%=pp[1][n]%>

                                </label>

                              </div>

                              </li>

                              <%@check<< pp[1][n]%>
                              <%end%>
                              <%@id.clear%>
                                </ul>
                           
                        </div>
                    </div>
                </div>
                <%t=t+1%>
                <%end%>
                
                              
                          <div class="clearfix"></div>

            </div>
            </div>
        </form>
             <div class="choose-container">
<a href="/products/main_category"><button class="btn btn-block btn-default hvr-sweep-to-right" controller="products" action="main_category">Choose Another Category</button></a>
               </div>
              
          <div class="clearfix"></div>
        </div>
<%end%>

 

   <%= yield %>
 
<div data-turbolinks="false">
  <a href="/" data-turbolinks="true"></a>
</div>

<div data-turbolinks="false">
  <a href=":" data-turbolinks="true"></a>
</div>

</body>
<script>
$(".menu-icon").click(function(){
    $(".sidebar").toggleClass("show-nav");
  $(".body-wrap").toggleClass("full-width");  
}); 
$(".menu-icon").click(function(){
    $(".filterbar").toggleClass("show-nav");
  $(".row").toggleClass("full-width");  
}); 
</script>
<script>

$(function(){
    $('.scroll').slimScroll({
        height: '380px'
    });
});
</script>
<script language="javascript">

 function validat()

 { var chks = document.getElementsByName('is[]');

 var checkCount = 0;

 for (var i = 0; i < chks.length; i++)

 { if (chks[i].checked)

 { checkCount++; } }

 if (checkCount < 1)

 { alert("Please Select at least one.");

 return false; }

 else { return true; } }

</script>